"""Art-direction judgments from visual inspection, not computed quality metrics.
Columns: ID | style | theme | animation | priority | intervention | evidence/action | preserve | stance | motion note | reference recommendation.
"""
ROWS = r'''
barricade_guard|8.5|9|8.5|P3|Internal shading/palette cleanup|Helmet silhouette and hammer read immediately; remove a few scattered visor/helmet specks and consolidate the shield's small metal patches.|Closed helmet, short hammer, small round shield, red cloth and compact scale.|Keep the compact defensive stance; equipment already distinguishes him from villagers.|Ground-strike Ability frames 6-12 are busy at the feet; retain contact but reduce loose sparks if polishing.|Useful secondary dull-iron reference; not a core addition.
barricade_villager|9|10|9|P3|Internal shading/palette cleanup|Face and cap are clean; the carried timber's many bright parallel cuts compete with the face. Combine internal log highlights while retaining log-end separation.|Cap, axe, armful of logs, rustic palette, original face and ready silhouette.|Keep now. A slight load-bearing shoulder lean is an optional later pose study, not required for cohesion.|Kneeling Ability is characterful and clearly separate from the axe attack; preserve folded leg and hand/tool contact.|Local workwear/prop reference only; Farmer already fills the core rustic role.
basket_villager|9.5|10|9|P3|Keep|Broad hat, small warm face and low basket communicate an ordinary local instantly. Berry accent is restrained.|Hat, basket volume, subdued clothing, berry cluster and hand-adjusted family style.|Keep; lowered basket already differentiates this silhouette from the pitchfork Farmer.|Keep the compact berry gather/release and rigid basket; do not add a noisy projectile trail.|Strong supporting villager reference; redundant with Farmer for core membership.
court_mage|8.5|9.5|8|P2|Internal shading/palette cleanup|Pale hood and cyan staff have a clear hierarchy; gold trim and bright garment edges could use fewer competing interior accents.|Pale hood, visible bearded face, cyan crystal staff, red lower fabric.|Keep the upright caster; no need to copy the Mender's open palm.|Ability frames 6-11 place cyan streaks across the torso and face; narrow their coverage while keeping the release cue.|Specialist cloth/magic reference after effects cleanup; not core.
crossbow_guard|9|9.5|9|P3|Keep|Kettle helmet, open face and horizontal crossbow form three clean masses. The wood/string contour remains readable across the poses.|Complete bow/string, open face, helmet and blue-gray uniform.|Keep the two-handed low guard; shared ranged discipline is appropriate.|Retain the restrained idle and visible weapon recoil; preserve the repaired lower bow edge.|Supporting rigid-prop reference; not an additional core anchor.
farmer|9.5|10|9.5|P3|Keep|Current ready pose has a large straw shape, clean face and one clear diagonal tool; cloth stays subordinate. An excellent expression of the game's ordinary-person charm.|User-adjusted face/idle, straw hat, exact pitchfork/prongs, skin and rustic materials.|Keep. The diagonal fork already supplies motion and personality.|Nine 130 ms idle exposures and compact 680 ms thrust sit naturally beside Rattlebones.|Retain existing supporting reference; formalize rustic clothing/skin and improvised equipment, not universal anatomy.
king|8.5|10|8|P2|Internal shading/palette cleanup|Crown, beard, red cape and broad armor establish authority; small gold/white plate accents compete at the waist. Merge minor accents without reducing rank.|Crown, gray beard, heavy body, royal red/gold, large sword and approved two-handed Bombardment.|Keep the upright planted authority; no exaggerated crouch.|AutoAttack/JudgmentStrike1 frame 5 and Strike2 frame 4 have large pale arcs. Keep force but open negative space around the head; preserve attack timing and both-hand contact.|Boss hierarchy reference, not the universal detail budget or attack-flash standard.
knight|9|9.5|9|P3|Keep|Large subdued helmet and red tabard are clear; sword identifies the role with very little texture.|Closed rounded helmet, simple plates, tabard and short sword.|Keep the disciplined stance; the simpler silhouette usefully precedes royal troops.|Compact slash and return remain consistent with the restrained idle.|Supporting common-armor example; Royal Swordsman is a more useful core royal example.
knight_captain|9|9.5|8.5|P3|Keep|Exposed face and tall plume distinguish the captain without excessive ornament. Face remains a useful focal patch.|Visible face, gray plume, red cape and sword.|Keep; face and plume already distinguish leadership. A commanding off-hand gesture can stay in Ability.|AutoAttack frame 5 has a broad bright arc; slight thinning is optional, not grounds to redraw the character.|Strong face/helmet combination; secondary only.
miner|9|10|8.5|P3|Keep|Cap candle, readable pick and simple face are a charming direct bridge to the mining zone; this is a better material anchor than highly textured fantasy miners.|Candle attachment, cap, pick, warm face, existing 96x80 canvas and drawn scale.|Keep the modest worker stance; do not imitate the dwarves' broader anatomy.|Preserve the intentional airborne Ability frame 4. Attack/Ability eyes become rounder; keep this as acting, avoiding further facial inflation.|Supporting mine-material reference, not a requirement that dwarves adopt human proportions.
pan_villager|9.5|10|9.5|P3|Keep|Distinct headscarf, simple expression and one large cool pan shape work beautifully. Existing flat pan center is readable cookware.|Original face and female identity, scarf shape, pan size/grip, iron ramp and planted boots.|Keep. The round low pan makes the silhouette distinct without an unusual pose.|Overhead attack carries the pan with the hand and returns cleanly; retain scarf restraint.|Retain existing supporting reference for cloth, faces and dull metal; never copy the pan as a shield.
royal_arbalist|8|9.5|8.5|P2|Internal shading/palette cleanup|White armor, visor bars, plume, crossbow and gold highlights create more small bright fragments than Royal Swordsman. Simplify helmet/gauntlet interior reflections first.|Enlarged approved helmet, red plume, full crossbow/string and royal identity.|Keep the ranged stance; it need not be dramatically different from Crossbow Guard.|Recoil remains clear; apply material cleanup consistently across Idle, AutoAttack and Ability, preserving the lower bow contour.|Not core; Royal Swordsman demonstrates royal armor more cleanly.
royal_arcanist|9|10|8.5|P3|Internal shading/palette cleanup|The Minister's warm face, red robe and single gold staff read well. Keep robe highlights subordinate to face and staff.|Current display name, existing face/hair, red/cream vestment and gold staff.|Keep the calm upright official's stance; expressive hand belongs in casting.|Restoration and Benediction share a strong gesture with distinct green/gold effects. Reduce overlapping rings only if they obscure hand/staff.|Secondary human caster; Mender adds more complementary simplicity to the core set.
royal_lancer|8.5|9.5|8.5|P3|Internal shading/palette cleanup|Strong lance and white helmet read clearly, but segmented shin/forearm highlights are busier than the torso. Merge small reflections.|Enlarged approved helmet, lance length, plume and compact royal body.|Keep upright reach specialist. Optional small shoulder turn only if side-by-side playtests confuse him with Spear Knight.|Wide attack canvas is necessary clearance, not a smaller character. Preserve full reach, contact and recovery.|Specialist reach/weapon reference; not core.
royal_standard_bearer|8.5|10|8.5|P3|Internal shading/palette cleanup|Banner gives an excellent role silhouette. Tiny armor spots and banner embroidery should remain less prominent than the pole, face plate and cloth triangle.|Banner emblem/shape, tall pole, white helmet, red cape and faction colors.|Keep the vertical standard; do not add a wide combat pose just for variety.|The flag's controlled tilt is readable; keep pole rigid and grip connected through Ability.|Specialist banner/cloth reference, not a general stance model.
royal_swordsman|9.5|9.5|9|P3|Keep|Large white helmet planes, clean dark visor and restrained red cape show how richer equipment can remain as readable as the villagers.|Simple helmet planes, visor, sword, cape and existing royal palette.|Keep the economical three-quarter ready pose.|Attack anticipation, extension and recovery are easy to follow; preserve arm/weapon continuity.|PROPOSE core addition for clean metal and royal hierarchy; do not copy white armor, closed face or pose to everyone.
shield_knight|7.5|9.5|8.5|P2|Partial redraw/simplification|Gold shield filigree and many trim fragments are the Dungeon's clearest internal-detail outlier. Redraw the emblem as a few connected gold masses with quiet steel around it.|Recognizable decorated shield, cross-like helmet trim, dark steel/red cloth and gold identity.|Keep initially. An optional shield-forward quarter turn could clarify defense, but is a separate all-state repose, not needed for cleanup.|Raised-shield Ability is good acting; retain the blue grant pulse and shield outline. Carry simplified ornament through every shield rotation.|Not core until ornament simplification; useful defensive-action study.
siege_sergeant|8.5|9.5|8.5|P3|Internal shading/palette cleanup|Beard, gloves and dark chest compress into one busy area. Separate beard from collar with a larger quiet plane and reduce small chest highlights.|Bearded face, red crest, heavy hammer and workmanlike blue/brown equipment.|Keep weight over the hammer; broader stance fits the heavy strike.|Keep the deliberate hammer lift/contact; reduce a few peripheral ground sparks if they cover the boots.|Secondary heavy-tool reference; not core.
spear_guard|9|9.5|9|P3|Keep|Simple open face, long spear and wooden round shield are clearly separated. A successful low-rank soldier.|Kettle helmet, wood shield, long spear and blue-gray cloth.|Keep the vertical guard position; reach is expressed during attack.|Long horizontal thrust stays readable in its padded canvas. Preserve the shaft as one rigid line.|Useful basic-spear example; not a core addition.
spear_knight|8|9.5|8.5|P3|Internal shading/palette cleanup|Gold edge lines cover helmet, spear, torso and legs. Reduce uninterrupted bright edging on nonfocal lower plates while retaining the faction vocabulary.|Red crest, gold-trimmed dark helmet, spear and knight proportions.|Keep the tall spear stance; same combat family does not demand a unique camera angle.|Retain the full thrust and attached plume; simplify trim consistently across rotations.|Not core; current detail density is less economical than Royal Swordsman.
town_marshal|9|10|9|P3|Keep|Broad belly, bald head, beard and handbell make a memorable civilian authority. Large areas are clean and expressive.|Bald head, beard, belly, bell and secondary weapon.|Keep; his open arms and round body already provide valuable variety.|Bell lift and small circular ringing accents communicate the ability without losing the face.|Excellent personality example; reserve rather than expanding the core set.
ancient_treant|7.5|10|7.5|P2|Internal shading/palette cleanup|Approved Old Stump has an excellent cut-trunk silhouette, but repeated bark striations compete with the face and limb masses. Merge bark into broad turning planes; keep only selected grooves.|Approved C identity, stump rings, branch crown, layered fungi, root arms and large footprint.|Keep the heavy crouched tree anatomy; no human stance.|Death frames 1-5 remain relatively upright and similar to a flinch. A later localized slumping/branch-settle ending would clarify defeat. Hit dust should not erase the stump face.|Specialist nonhuman anatomy only; not a core rendering anchor yet.
barkhide_warden|7.5|9.5|8|P2|Internal shading/palette cleanup|Face, bark shoulder layers and shield grain all have similar busy contrast. Quiet interior bark lines and keep a stronger separation around the olive face.|Broad orc body, large wooden shield, leaf/bark armor and earth palette.|Keep asymmetric shield-first mass; it already says protector.|Channel shield movement is readable; keep wood/arm contact. Simplification must follow shield turns, including fallen Death poses.|Not core; Trailguard gives a cleaner orc/material anchor.
briar_archer|8.5|9.5|8.5|P3|Internal shading/palette cleanup|Pale hair against dark wine cloth is a good focal arrangement; a few pointed cloth/strap fragments crowd the waist and bow hand.|Silver hair, dark bow, wine-red hood/cape and lean elf anatomy.|Keep the aimed stance; distinguish from Scout through costume and attack character, not a new camera.|ChannelStart and Release show a clear draw/release. Preserve the bowstring and hand at all keys; simplify only interior folds.|Specialist dark archer example; Scout is the cleaner optional bow reference.
briar_matriarch|7.5|10|8|P2|Partial redraw/simplification|Crown, hair, fingers and many long robe accents make an elegant but more illustrative figure. Consolidate robe into three or four major panels and simplify internal hair strands; retain tall proportions.|Approved queenly identity, thorn crown, pale hair/face, staff, long gown and 96x96 footprint.|Keep tall open-handed authority; do not shorten her into a villager.|Channel/Release gestures are clear; carry simpler robe planes through Hit, Death and casting. Do not enlarge effects to compensate for a small face.|Apex silhouette reference only; not the global shading standard.
elven_mender|9.5|10|9|P3|Keep|Open face, cream shoulder cloth, muted rose robe and simple staff separate cleanly. Calm friendly fantasy survives at native size.|Approved face, ears, staff, cream/rose materials and slim anatomy.|Keep the welcoming free hand and upright staff; an excellent purposeful alternative to weapon-ready humans.|All eight states maintain recognizable face/costume; compact channel and recovery are well suited to the family.|PROPOSE core addition for readable support/caster design and quiet cloth; do not copy elf anatomy or cream clothing globally.
elven_scout|9|9.5|8.5|P3|Keep|Hair, ear, drawn bow and blue-gray clothing read cleanly with little surface noise. Bow/string legitimately add fine lines.|Approved face/hair, long ear, bow, quiver and light equipment.|Keep the poised archer stance; useful contrast to standing melee troops.|Idle opens the bow/body more than the tiny Rattlebones settle; acceptable specialist acting, but do not amplify it further.|Strong reserve reference for bow/hand relationship; omit from core to avoid redundancy with Mender and Farmer.
elven_thornkeeper|8.5|9.5|8.5|P3|Internal shading/palette cleanup|Curved thorn growth identifies the kit, but thin branch tips and small waist details can become tangled. Group branch interiors while retaining the outer hook silhouette.|Approved hair, ears, green tunic, thorn-loop prop and slim body.|Keep the guarded three-quarter stance; prop carries the distinction.|Ability spreads the thorn silhouette clearly. Preserve face and hand connections while simplifying branch texture across all states.|Secondary organic-tool reference; not core.
orc_berserker|8.5|9.5|8.5|P3|Internal shading/palette cleanup|Large jaw, muscular shoulders and heavy axe communicate force. Small muscle/strap accents can be joined into larger skin and leather planes.|Approved olive skin, tusked face, axe, red loincloth and broad build.|Keep the forward-ready weight; anatomical difference is intentional.|Ability's lifted chest/shout distinguishes rage without requiring a new identity. Keep grounded return and axe grip.|Specialist broad-body acting; Trailguard is the more restrained core anchor.
orc_bloomcaller|8|10|8.5|P2|Internal shading/palette cleanup|Strong pale hood/robe and flower staff make a charming ritualist. Numerous garment folds, bead-like details and floral colors divide attention.|Approved hood, face, cream/rose robe, flower staff and orc anatomy.|Keep open casting hand; no need to mimic Mender exactly.|Hand-to-mouth attack and raised-flower Ability are characterful; preserve these, simplifying repeated cloth accents throughout.|Not core; useful thematic contrast, with less restrained surface treatment.
orc_drummer|8.5|10|8|P3|Internal shading/palette cleanup|Big drumhead and paired sticks explain the role immediately. Simplify drum lacing to a few clear diagonals and quiet chest straps.|Approved drum size, two sticks, hair tie, olive face and leather palette.|Keep planted performer stance; slight torso angle already creates personality.|Ability's raised-stick preparation reads well. Death settles into a crouch that could use a clearer final head/drop beat if revised.|Specialist instrument acting; not core.
orc_rootbinder|8.5|9.5|8.5|P3|Internal shading/palette cleanup|Blue robe and pale fur shoulder separate well, but twig fingers/staff and small face shadows could be quieter. Group fur into a few broad tufts.|Approved olive face, blue robe, pale shoulder fur and branching staff.|Keep the hunched shaman stance; useful contrast to Trailguard.|Staff raise and channel continuity read clearly; preserve the staff's full outline rather than attaching isolated new twigs.|Supporting shaman anatomy/materials; not core.
orc_trailguard|9|9.5|9|P3|Keep|Broad jaw, simple leather mass, cool shoulder plate and pale axe head stay distinct. Shows that an orc can match the rendering without copying human proportions.|Approved tusks, olive skin, broad build, leather armor and two-handed axe.|Keep the stable wide stance; it expresses weight rather than pose repetition.|Clear overhead anticipation, strike and compact recovery; Death resolves into an unmistakable prone silhouette.|PROPOSE core addition for broad nonhuman bodies and leather/iron separation; do not copy green skin, axe or stance to all monsters.
snapvine|8.5|10|6.5|P1|Partial redraw/simplification|The curved stalk and toothed mouth are a strong simple design. Preserve the still; concentrate work on Death's detached root-like piece above the head in frames 2-6.|Approved mouth, teeth rhythm, curved green stalk, leaves and grounded root footprint.|Keep plant anatomy; no humanoid ready pose.|Replace the confusing airborne root cluster with an attached wilt/collapse progression or clearly separated small debris. Inspect source slicing first; do not assume a generation defect from names.|Useful plant silhouette, not a motion reference until Death is corrected.
breakwater_captain|8|10|8.5|P2|Internal shading/palette cleanup|Shark head, coral trident and shell shield provide strong identity. Shield's many bright checkered segments pull attention from the face; use broader shell planes.|Shark profile, shield silhouette, red sash, trident and broad captain stance.|Keep shield-bearing authority; it need not resemble Shield Knight's anatomy.|Raised shield and channel hold are legible. Apply shell cleanup across every angle; preserve the trident's clean thrust.|Role/silhouette reference only; not core rendering.
conch_marshal|8|10|8.5|P2|Internal shading/palette cleanup|Red/cream crest and conch are distinctive but share many alternating small stripes. Quiet lower costume marks and keep the conch opening clear against the head.|Fan crest, conch instrument, coral-red palette and narrow body.|Keep upright horn-player stance; do not overpose the legs.|ChannelStart brings conch to mouth convincingly. Preserve mouth contact and head shape through Release/Interrupt.|Specialist musical signaling, not core.
hammerhead_bruiser|8.5|10|8.5|P3|Internal shading/palette cleanup|Hammer-shaped head and compact mallet give an immediate chunky silhouette. Reduce tiny leather-buckle and abdominal contour noise.|Distinct wide head, pale throat, blue-gray skin, mallet and broad body.|Keep the grounded heavy stance; species shape already supplies variety.|Overhead mallet swing is readable; no need to inflate idle motion or add broad flashes.|Potential heavy marine reference, but Pearl Thief adds a more economical nonhuman core example.
lantern_warden|7|10|8|P1|Partial redraw/simplification|Lure, toothed face, spined back, shell disks and carried coffer all compete. Preserve all major identity parts but simplify shell interiors, dorsal ornaments and coffer trim; make lure/face the first read.|Angler lure, purple body, coffer, recognizable teeth and bulky bent silhouette.|Keep hunched coffer carrier; reposition the coffer slightly only if hand/face separation remains poor after internal cleanup.|Coffer opens clearly in ChannelHold. Preserve hinge/grip across opening and attack; avoid independent ornament flicker.|Not core; the main Court density outlier.
moray_siphoner|9|10|8.5|P3|Keep|Long pale throat, green coiled body and coral staff create clear large shapes. Good proof that a nonhuman silhouette need not be heavily textured.|Eel head, pale underside, curled floor contact, burgundy cloth and coral staff.|Keep the coiled upright serpent pose.|Body flex and mouth opening are coherent; ensure future changes retain the floor contact and do not turn the idle into floating.|Strong reserve nonhuman reference; core shortlist kept smaller with Pearl Thief.
needlefin_skirmisher|8.5|10|8.5|P3|Keep|Long snout, sharp fins and spare equipment create a fast, recognizable silhouette. Cool planes remain mostly connected.|Needle snout, small orange fin accents, narrow legs and blue-gray skin.|Keep the light forward stance; this is appropriate anatomy, not off-style camera work.|Forward attack extension reads well; preserve snout length and ankle contacts.|Specialist agile marine body; not core.
pearl_cantor|8.5|10|8.5|P3|Internal shading/palette cleanup|Golden seahorse head and dark teal robe are a strong two-mass design. Thin bright robe piping can be consolidated around the central fold.|Seahorse snout, curled tail, crook staff, pale head and teal robe.|Keep the stately vertical caster; it contrasts with crawling/coiled Court enemies.|Curled appendage lifts distinctly in casting; preserve its identity through channel and collapse.|Strong caster reserve; Mender fills core cloth and Pearl Thief fills marine simplicity.
pearl_thief|9.5|10|9|P3|Keep|Large quiet purple head, tiny mischievous face, bright pearl and curling limbs feel closest to the playful monster identity. Very little decoration is wasted.|Head silhouette, minimal face, pearl/coffer relationship, hook and tentacle shapes.|Keep low asymmetric tentacle stance; do not add humanoid legs or a skeleton face.|Casting and death retain the same identity; little accents remain subordinate to the large head.|PROPOSE core addition for whimsical marine/nonhuman simplicity; do not copy purple color, eye placement or tentacles globally. Membership and broader artwork approval remain separate.
puffer_sentinel|8.5|10|6.5|P1|Partial redraw/simplification|Base pose is appealing, but inflation becomes a dominant pale disk and the face nearly disappears into its upper rim. Restore a clearly readable eye/mouth cluster and dark contour separation while retaining the expanded silhouette.|Orange/cream puffer identity, spines, staff, normal face, deliberate inflated size and gameplay meaning.|Keep base stance and inflated round body; do not replace the intentional state change with ordinary breathing.|Prioritize InflatedIdle, InflatedAttack, ChannelStart/Hold, Ability, Release and Interrupt. Keep face registration through growth/shrink; do not make it jump between unrelated positions.|Not core until alternate-state identity reads clearly.
queen_nacre|8|10|8.5|P2|Internal shading/palette cleanup|Fan crown/fins, trident and wine-red gown establish a marine queen. Fine gold edges and repeated fin stripes compete with the small face; reduce lower-gown trim before touching the iconic crown.|Pale fish face, royal fan silhouette, trident, red/cream/gold scheme and tall authority.|Keep upright courtly stance; crown/fan already creates a distinct apex silhouette.|DepthsRelease and thrust keep the trident readable. Carry cleaner robe/fins through channel turns and prone Death.|Apex marine silhouette reference; not global detail standard.
reef_netweaver|8.5|10|8.5|P2|Internal shading/palette cleanup|Simple shark body is strong; numerous tiny net knots are the noisy component. Use fewer readable mesh cells and a clear top grip.|Shark head, carried hanging net, pale throat and slim blue-gray body.|Keep net arm slightly clear of torso; a local forearm separation is enough if needed, not a whole repose.|Channel extension and retrieval are readable; simplified mesh must maintain consistent knot topology between frames.|Specialist net/prop example after cleanup; not core.
reef_spearman|9|10|8.5|P3|Keep|Orange crest against green skin and burgundy cloth creates a readable ordinary marine soldier. Equipment is economical.|Crest, fish face, coral trident and slim stance.|Keep modest diagonal spear stance; faction and anatomy do the differentiating.|Long thrust stays attached to the hands and returns to the same ready pose.|Good marine infantry reserve; not core expansion.
shellback_porter|8|10|8.5|P2|Internal shading/palette cleanup|Big shell is an excellent load-bearing silhouette; near-equal warm tones in shell, arm and face reduce separation. Darken overlap divisions and simplify repeated shell highlights.|Shell dome, forward face, mallet, orange shell ramp and bowed body.|Keep the forward load-bearing lean; one of the most purposeful poses.|Shell and body stay coherent through swing and fall. Preserve shell mass instead of smoothing it into a backpack.|Specialist shell/material reference after cleanup; not core.
skittercrab|9|10|8.5|P3|Keep|Broad claws and small low body read instantly; warm shell planes are connected and playful.|Low footprint, two clear claws, eye stalks and sand/coral colors.|Keep the low crab stance; never force it onto the humanoid floor silhouette.|Claw attack is readable; final Death is subtle, so a more visibly lowered claw is an optional later terminal-pose polish.|Strong reserve small-creature reference; no need to enlarge the core set further.
bore_engineer|7.5|10|8.5|P2|Internal shading/palette cleanup|Drill tip and orange power chamber identify the job, but goggles, beard and machinery carry many tiny equally sharp lines. Simplify beard strands and glove/weapon overlaps.|Dwarf proportions, goggles, gray beard, drill spiral, warm power cell and two-hand grip.|Keep braced tool-forward stance; do not slim him toward the villagers.|Normal and ore-charged thrusts retain a clear tip. Keep powered accents concentrated at the chamber/contact, not across the face.|Not core; study Miner for material economy and Trailguard for broad-body grouping.
grand_delver|8|10|8|P2|Internal shading/palette cleanup|The suit already has broad useful chest planes; repeated joint/rivet highlights and dark round idle smoke distract from the small pilot face. Simplify joint glints and smoke clusters.|Huge drill, asymmetric claw, exposed dwarf face, orange power accents and mechanical mass.|Keep heavy broad stance; no anatomy normalization.|Idle smoke is more prominent than the body's settle; reduce its contrast/occupied area. Preserve powered reach, claw claim and Core poses; never alter contact timing through art cleanup.|Useful large-machine silhouette reference; not core character rendering.
obsidian_sentinel|7.5|9.5|8|P2|Partial redraw/simplification|Large shoulder rocks, round plates and piston joints create a strong golem but too many small bevels. Flatten nonfocal armor planes and clarify stone versus metal joints.|Massive dark body, angular shoulders, orange slit/core, piston limbs and heavy fists.|Keep square weight-bearing stance; the absence of a human face is intentional.|Slam and Devour poses have distinct silhouettes. Preserve their difference; remove only excess micro-bevels across all rotations.|Not core; machinery/stone specialist after cleanup.
ore_hauler|8.5|10|8.5|P3|Internal shading/palette cleanup|Pale beard, rounded load and orange ore tell the role well. Quiet the basket straps and small alternating ore chips around the main chunks.|Large carried load, pale beard, cap, orange ore and stocky posture.|Keep forward burdened lean; strong differentiation from armed dwarves.|Ore scattering in Death is readable. Keep the load attached and simplify straps consistently during reaching.|One of Ironvein's stronger candidates; reserve load/prop reference, pending art approval.
packbeetle|8|10|8|P2|Internal shading/palette cleanup|Low beetle body and ore panniers are recognizable, but legs and dark shell edges merge against dark backgrounds. Create a few broader upper shell planes and simplify pack fixtures.|Six-legged beetle read, low silhouette, dark carapace, ore load and orange eyes.|Keep quadrupedal/insect support footprint; do not give it a humanoid stance.|Attack is deliberately compact; make leg compression readable without lifting the whole load. Death collapse is clear enough to preserve.|Specialist pack-creature reference after value separation; not core.
pickaxe_delver|8.5|10|8.5|P3|Internal shading/palette cleanup|Large beard, simple pick and broad workwear mostly fit the family. Quiet little chest/strap facets and keep the face distinct from the beard.|Pick length/head, lamp helmet, brown beard and short broad body.|Keep worker's planted swing stance.|OreChargedAutoAttack frames 5-7 are much brighter than ordinary attack; reduce the arc to a compact connected sweep while preserving the powered cue.|Strong supporting dwarf baseline; not core until art selection receives approval.
powder_sapper|8.5|10|8|P3|Internal shading/palette cleanup|Wild red hair, round goggles and paired explosives have strong personality. Simplify small belt rectangles and beard hatching; protect the fuse silhouette.|Wild hair, goggles, two bombs, fuse and compact dwarf body.|Keep outward hands and eager lean; good purposeful variety.|Channel pose brings hands together clearly. Death ends in a brief crouch; a stronger head drop would better separate defeat from preparation.|Strong Ironvein personality reserve; not core rendering standard.
rail_switcher|8|10|8|P2|Internal shading/palette cleanup|Cap and green goggles distinguish the operator, but the chest device, gloves and beard compress into a busy dark oval. Separate the hand/device boundary and quiet minor fittings.|Rail cap, green lenses, controller/device, dark coat and stout legs.|Keep operator stance; if polishing pose, turn only the control panel outward enough to reveal its function.|Release device gesture is subtle; reinforce hand-to-control contact rather than making the whole body swing.|Not core; useful specialist prop concept.
rivet_gunner|7.5|9.5|8.5|P2|Internal shading/palette cleanup|Weapon, gloves, beard and chest overlap in one gold-brown cluster. Broaden the gun's main metal plane and separate it from the supporting forearm; remove tiny beard specks.|Goggles, orange-brown beard, rivet weapon, blue-gray sleeves and two-hand grip.|Keep horizontal braced firing stance; plausible shared posture with Bore Engineer.|Short recoil and directional muzzle flash work. Keep normal/charged distinction without a larger explosion.|Not core; the turret demonstrates the machinery more economically.
rivet_turret|8.5|10|8.5|P3|Keep|Barrel, rectangular warm power housing and stable legs read at a glance. One of the cleaner machine designs in the cast.|Mechanical barrel, amber housing, leg footprint and machine-only identity.|Keep planted tripod-like support; no character pose required.|Recoil, powered flash and mechanical collapse are easy to distinguish. Preserve the muzzle as the flash origin.|Best current Ironvein machine reserve; proposed core membership deferred pending artwork review and to keep shortlist small.
seismic_smith|6.5|9.5|8|P1|Partial redraw/simplification|Face sits inside dense dark beard/chest texture; chain-like torso marks and heavily beveled hammer dilute the strong arm/hammer silhouette. Redraw interior beard and shirt into broad masses; isolate eyes/nose against one skin plane.|Powerful arms, black beard, heavy rune hammer, orange focal inset, dwarf width and worker character.|Keep broad hammer-bearing stance. Do not solve shading noise by changing species proportions.|Hammer lift/contact already reads clearly. Propagate simpler beard/chest/hammer planes through Ability and charged attack; preserve the hand grip and repaired edge.|Not core in current state; strongest Ironvein candidate for a targeted internal redraw.
siege_machinist|7|10|8|P2|Partial redraw/simplification|Wrench silhouette is excellent; toolbelt, backpack tubes, goggles and beard all carry tiny edge accents. Redraw the belt/backpack interiors with fewer larger parts and a quiet torso.|Large wrench, goggles, gray beard, blue machinery pack, stocky build and assembler identity.|Keep wrench-up ready stance; distinguish from gunner through the prop, not an exaggerated lean.|Assemble and Prime gestures are close in body read; emphasize distinct wrench/hand key poses in a later local action pass, preserving timings.|Not core; strong concept needing restrained execution.
stonewright|8|10|8|P2|Internal shading/palette cleanup|Wide helmet and small hammer provide a good silhouette. Twin braids and repeated armor borders can be simplified to larger connected clusters.|Wide-brim helmet, orange braids, compact hammer, dark apron and broad stance.|Keep sturdy craftsperson stance; do not copy Seismic Smith's huge hammer.|Idle has three exposures totaling 790 ms, unlike nearby dwarf idles. Review whether the short settle feels rushed in playback; do not retime automatically from frame count.|Supporting dwarf variation; not core.
vein_surveyor|8.5|10|8.5|P3|Internal shading/palette cleanup|Pale beard and gold lens stand out against the blue hood. Rolled map and satchel are clear; simplify little belt/strap crossings.|Blue hood, white beard, gold inspection lens, map and dwarf anatomy.|Keep the inspecting forward lean; purposeful role distinction.|Release presents the map/lens clearly; preserve small measured gestures and prop continuity.|Good intellectual/utility dwarf reserve; not core expansion.
bardley|9.5|10|9.5|P3|Keep|Asymmetric lime slime, plum hat/cape and little instrument are bold, cheerful and extremely readable. Large body areas remain quiet.|Exact slime contour, hat/feather, instrument, face, saturated body and current grounded production baseline.|Keep asymmetry and low body; never make a human pose template.|Preserve compact grounded idle and musical cast. Historical static placement-pending file is not the current animation alignment authority.|Existing palette/identity reference; useful alongside Rattlebones, without expanding enemy core shortlist.
gideon_glass|8.5|10|9|P3|Internal shading/palette cleanup|Large hat, pale feather and blue lens create a memorable automaton. Thin coat/cane and small brass body details are less readable than Rattlebones; reduce only optional coat specks if needed.|Approved detailed design, hat/feather silhouette, lens, brass face, split coat and thin cane. The rejected simplified redesign stays rejected.|Keep elegant narrow side-facing stance; do not force the large-head villager proportions.|Cast and recovery stay controlled. Preserve the intentional still Hold pose and avoid inventing breathing or camera motion.|Player specialist only; not a universal anatomy/detail standard.
skeleton|10|10|10|P3|Keep|Primary golden standard: clear skull, cyan focal eyes, tiny crown and red cape; broad bone planes and sparse accents create instant identity.|All approved Rattlebones anatomy, palette, face, crown, cape, scale and motion.|Keep exactly; never redesign him to justify mismatched cast art.|Use the current nine-frame grounded idle and compact royal command as motion anchors, not universal frame-count laws.|PRIMARY GOLDEN STANDARD, explicitly established by this task.
grand_delver_pilot|8|9.5|8|P3|Keep|Small pilot in a large 112x112 transition canvas is intentional. Judge drawn bounds at shared pixel scale; do not enlarge him merely to fill the canvas.|Orange beard, helmet, pilot identity, small scale relative to suit and continuous ejection placement.|Keep small braced pilot stance. Inspect runtime floor/HP spacing before any pose work; correct layout instead of redrawing if a placement defect is later confirmed.|Eject frames 5-14 coherently reveal the pilot and falling suit; verify optional phase continuity only if remount is enabled later. No import defect is established here.|Not core; disabled experimental alternate, lower remediation priority.
grand_delver_reserve|7.5|9.5|8|P3|Internal shading/palette cleanup|Reserve suit preserves the boss identity but has more fine contour highlights and smoke. Use the same simplified joint/metal scheme as the primary suit.|Distinct reserve machine, orange beard, drill/claw, smoke-stack and transition silhouette.|Keep heavy stance; do not change relative pilot scale.|Remount deliberately brings the suit in from off-canvas; edge entry is not automatically clipping damage. Review idle/action seams before enabling the experiment.|Not core; disabled alternate, review after the active boss.
'''

def assessments():
    result={}
    for row in ROWS.strip().splitlines():
        parts=row.split('|')
        assert len(parts)==11,(len(parts),parts[0])
        ident,style,theme,animation,priority,intervention,evidence,preserve,stance,motion,golden=parts
        result[ident]=dict(style=float(style),theme=float(theme),animation=float(animation),priority=priority,
            intervention=intervention,evidence=evidence,preserve=preserve,stance=stance,motion=motion,golden=golden,
            review_status='Fallback/ready and all bound sprite drawing rows visually inspected; timing read from serialized clips. Not a fresh Unity playback test.')
    assert len(result)==67,len(result)
    return result
