using System;
using System.Collections.Generic;
using UnityEngine;

public partial class BoardController
{
    public event Action<GemMatchVFXContext>
        GemMatchVFXRequested;

    public event Action<BombVFXContext>
        BombVFXRequested;

    /*
     * Directional bomb VFX is runtime-generated by BombVFXController.
     * Its beam currently lasts 0.36s and its longest white pixel can
     * live for 0.375s. Keep the board still until that longest visible
     * piece has finished so refill gems never fall through the blast.
     *
     * This hold is registered for ordinary bomb detonations and for ability
     * chains that genuinely activate a directional bomb. Color-crystal bomb
     * sequences already own their own presentation cadence and should not be
     * serialized into one slow bomb-at-a-time sequence by this refill gate.
     */
    private const float
        DirectionalBombMaximumVisualLifetime =
            0.375f;

    /*
     * Coroutine waits and Update-driven particles land on rendered frames,
     * not exact floating-point timestamps. A tiny safety beat guarantees
     * gravity starts after the final VFX frame even at low frame rates.
     */
    private const float
        BombRefillSafetyPadding =
            0.015f;

    private float
        directionalBombRefillHoldUntilTime;

    private float
        poisonBombRefillHoldUntilTime;

    private void ReportMatchesToVFX(
        HashSet<Gem> matches,
        int cascadeDepth)
    {
        if (matches == null ||
            matches.Count == 0)
        {
            return;
        }

        /*
         * An earned directional bomb cannot detonate before some board
         * interaction has happened. Lazily create and prewarm its small VFX
         * pool on the first real match instead of paying that setup cost on
         * the bomb's impact frame.
         */
        EnsureBombVFXController();

        List<List<Gem>> matchGroups =
            BuildConnectedMatchGroups(
                matches
            );

        foreach (
            List<Gem> group
            in matchGroups)
        {
            if (group == null ||
                group.Count < 3)
            {
                continue;
            }

            Gem firstGem =
                group[0];

            if (firstGem == null)
            {
                continue;
            }

            Vector3[] worldPositions =
                new Vector3[group.Count];

            for (int index = 0;
                 index < group.Count;
                 index++)
            {
                Gem gem =
                    group[index];

                worldPositions[index] =
                    gem != null
                        ? gem.transform.position
                        : Vector3.zero;
            }

            GemMatchVFXRequested?.Invoke(
                new GemMatchVFXContext(
                    firstGem.Type,
                    group.Count,
                    cascadeDepth,
                    worldPositions,
                    matchFlashDuration
                )
            );
        }
    }

    private void ReportBombClearSetToVFX(
        HashSet<Gem> expandedClearSet,
        BoardClearSource clearSource)
    {
        if (expandedClearSet == null ||
            expandedClearSet.Count == 0)
        {
            return;
        }

        /*
         * These are pathways where bombs in the expanded clear set genuinely
         * activate. Double-crystal/environmental sweeps can erase a special
         * without activating it and therefore remain excluded.
         */
        if (clearSource != BoardClearSource.Bomb &&
            clearSource != BoardClearSource.ColorCrystal &&
            clearSource != BoardClearSource.Ability)
        {
            return;
        }

        PoisonBombVFXController poisonController =
            null;

        foreach (Gem gem in expandedClearSet)
        {
            if (gem == null)
            {
                continue;
            }

            bool isDirectionalBomb =
                gem.SpecialType ==
                    GemSpecialType.RowBomb ||
                gem.SpecialType ==
                    GemSpecialType.ColumnBomb;

            bool isPoisonBomb =
                gem.SpecialType ==
                    GemSpecialType.PoisonBomb;

            if (!isDirectionalBomb &&
                !isPoisonBomb)
            {
                continue;
            }

            if (isDirectionalBomb)
            {
                EnsureBombVFXController();
            }
            else
            {
                poisonController =
                    poisonController != null
                        ? poisonController
                        : EnsurePoisonBombVFXController();
            }

            /*
             * Poison's sprite burst begins at the same board-owned shatter
             * moment that commits its status effect: after the white flash and
             * hold. Directional beams retain their established flash timing.
             */
            float startDelay =
                isPoisonBomb
                    ? matchFlashDuration +
                      matchWhiteHoldDuration
                    : matchFlashDuration;

            BombVFXContext context =
                new BombVFXContext(
                    gem.SpecialType,
                    gem.transform.position,
                    startDelay,
                    gem.Column,
                    gem.Row
                );

            BombVFXRequested?.Invoke(
                context
            );

            bool shouldHoldNormalRefill =
                clearSource ==
                    BoardClearSource.Bomb ||
                clearSource ==
                    BoardClearSource.Ability;

            if (!shouldHoldNormalRefill)
            {
                continue;
            }

            if (isDirectionalBomb)
            {
                RegisterDirectionalBombRefillHold(
                    context.StartDelay
                );
            }
            else if (poisonController != null &&
                     poisonController.isActiveAndEnabled &&
                     poisonController
                         .HasUsablePoisonBurstFrames)
            {
                RegisterPoisonBombRefillHold(
                    context.StartDelay,
                    poisonController.MainBurstDuration
                );
            }
        }
    }

    private void RegisterDirectionalBombRefillHold(
        float vfxStartDelay)
    {
        float visualEndTime =
            Time.time +
            Mathf.Max(
                0f,
                vfxStartDelay
            ) +
            DirectionalBombMaximumVisualLifetime +
            BombRefillSafetyPadding;

        directionalBombRefillHoldUntilTime =
            Mathf.Max(
                directionalBombRefillHoldUntilTime,
                visualEndTime
            );
    }

    private void RegisterPoisonBombRefillHold(
        float vfxStartDelay,
        float mainBurstDuration)
    {
        if (mainBurstDuration <= 0f)
        {
            return;
        }

        /*
         * Only the main sprite burst delays normal refill. The optional
         * residue deliberately continues while gravity runs and removes itself
         * cell-by-cell as replacement gems visibly land.
         */
        float visualEndTime =
            Time.time +
            Mathf.Max(0f, vfxStartDelay) +
            mainBurstDuration +
            BombRefillSafetyPadding;

        poisonBombRefillHoldUntilTime =
            Mathf.Max(
                poisonBombRefillHoldUntilTime,
                visualEndTime
            );
    }

    private float
        GetDirectionalBombRefillHoldRemaining()
    {
        return Mathf.Max(
            0f,
            directionalBombRefillHoldUntilTime -
            Time.time
        );
    }

    private float
        GetPoisonBombRefillHoldRemaining()
    {
        return Mathf.Max(
            0f,
            poisonBombRefillHoldUntilTime -
            Time.time
        );
    }

    private void EnsureBombVFXController()
    {
        if (GetComponent<BombVFXController>() !=
            null)
        {
            return;
        }

        /*
         * The directional effect is completely runtime-generated, so the board
         * does not need a prefab reference or scene migration.
         */
        gameObject.AddComponent<
            BombVFXController
        >();
    }

    private PoisonBombVFXController
        EnsurePoisonBombVFXController()
    {
        PoisonBombVFXController controller =
            GetComponent<PoisonBombVFXController>();

        if (controller != null)
        {
            return controller;
        }

        /*
         * Runtime fallback keeps missing optional presentation harmless. A
         * scene/prefab should serialize this component when final sprite frames
         * are assigned; an auto-added empty controller simply skips the effect.
         */
        return gameObject.AddComponent<
            PoisonBombVFXController
        >();
    }
}
