using System;
using System.Collections.Generic;
using UnityEngine;

public partial class BoardController
{
    public event Action<GemMatchVFXContext>
        GemMatchVFXRequested;

    public event Action<BombVFXContext>
        BombVFXRequested;

    /*
     * Directional bomb VFX is runtime-generated by BombVFXController.
     * Its beam currently lasts 0.36s and its longest white pixel can
     * live for 0.375s. Keep the board still until that longest visible
     * piece has finished so refill gems never fall through the blast.
     *
     * This hold is registered only for normal BoardClearSource.Bomb
     * detonations. Color-crystal bomb sequences already own their own
     * presentation cadence and should not be serialized into one slow
     * bomb-at-a-time sequence by this refill gate.
     */
    private const float
        DirectionalBombMaximumVisualLifetime =
            0.375f;

    /*
     * Coroutine waits and Update-driven particles land on rendered frames,
     * not exact floating-point timestamps. A tiny safety beat guarantees
     * gravity starts after the final VFX frame even at low frame rates.
     */
    private const float
        DirectionalBombRefillSafetyPadding =
            0.015f;

    private float
        directionalBombRefillHoldUntilTime;

    private void ReportMatchesToVFX(
        HashSet<Gem> matches,
        int cascadeDepth)
    {
        if (matches == null ||
            matches.Count == 0)
        {
            return;
        }

        /*
         * An earned bomb cannot detonate before some board
         * interaction has happened. Lazily create and prewarm
         * its small VFX pool on the first real match instead of
         * paying that setup cost on the bomb's impact frame.
         */
        EnsureBombVFXController();

        List<List<Gem>> matchGroups =
            BuildConnectedMatchGroups(
                matches
            );

        foreach (
            List<Gem> group
            in matchGroups)
        {
            if (group == null ||
                group.Count < 3)
            {
                continue;
            }

            Gem firstGem =
                group[0];

            if (firstGem == null)
            {
                continue;
            }

            Vector3[] worldPositions =
                new Vector3[group.Count];

            for (int index = 0;
                 index < group.Count;
                 index++)
            {
                Gem gem =
                    group[index];

                worldPositions[index] =
                    gem != null
                        ? gem.transform.position
                        : Vector3.zero;
            }

            GemMatchVFXRequested?.Invoke(
                new GemMatchVFXContext(
                    firstGem.Type,
                    group.Count,
                    cascadeDepth,
                    worldPositions,
                    matchFlashDuration
                )
            );
        }
    }

    private void ReportBombClearSetToVFX(
        HashSet<Gem> expandedClearSet,
        BoardClearSource clearSource)
    {
        if (expandedClearSet == null ||
            expandedClearSet.Count == 0)
        {
            return;
        }

        /*
         * These are the two current pathways where a row or
         * column bomb in the expanded set genuinely detonates.
         *
         * Double-crystal sweeps can erase a bomb without firing
         * its directional effect, so they intentionally do not
         * produce a row/column beam here.
         */
        if (clearSource != BoardClearSource.Bomb &&
            clearSource != BoardClearSource.ColorCrystal)
        {
            return;
        }

        /*
         * Future abilities may be able to create or detonate a
         * bomb without a previous match, so retain this fallback.
         */
        EnsureBombVFXController();

        foreach (Gem gem in expandedClearSet)
        {
            if (gem == null ||
                (
                    gem.SpecialType !=
                        GemSpecialType.RowBomb &&
                    gem.SpecialType !=
                        GemSpecialType.ColumnBomb
                ))
            {
                continue;
            }

            BombVFXContext context =
                new BombVFXContext(
                    gem.SpecialType,
                    gem.transform.position,
                    matchFlashDuration
                );

            BombVFXRequested?.Invoke(
                context
            );

            if (clearSource ==
                BoardClearSource.Bomb)
            {
                RegisterDirectionalBombRefillHold(
                    context.StartDelay
                );
            }
        }
    }

    private void RegisterDirectionalBombRefillHold(
        float vfxStartDelay)
    {
        float visualEndTime =
            Time.time +
            Mathf.Max(
                0f,
                vfxStartDelay
            ) +
            DirectionalBombMaximumVisualLifetime +
            DirectionalBombRefillSafetyPadding;

        directionalBombRefillHoldUntilTime =
            Mathf.Max(
                directionalBombRefillHoldUntilTime,
                visualEndTime
            );
    }

    private float
        GetDirectionalBombRefillHoldRemaining()
    {
        return Mathf.Max(
            0f,
            directionalBombRefillHoldUntilTime -
            Time.time
        );
    }

    private void EnsureBombVFXController()
    {
        if (GetComponent<BombVFXController>() !=
            null)
        {
            return;
        }

        /*
         * The effect is completely runtime-generated, so the
         * board does not need a new prefab reference or scene
         * setup. Existing scenes therefore receive it without
         * any serialized migration.
         */
        gameObject.AddComponent<
            BombVFXController
        >();
    }
}
